defmodule Mjolnir.Forge.Authoring do
  @moduledoc """
  Writes Forge-authored declaration files — the machinery behind `adopt` and
  `overwrite-decl-from-observed`.

  ## One file per adopted resource

  Rather than parse and rewrite hand-written `.exs` modules (which would mean
  embedding an Elixir parser), Forge owns a dedicated file per adopted
  resource: `<declarations_path>/forge-adopted-<slug>.adopted.exs`, where
  `slug` is a deterministic hash of `(host, kind, id)`. Each file is a complete
  module declaring exactly one resource.

  This keeps the boundary crisp: **Forge only ever edits files it authored**
  (those ending in `.adopted.exs`). Hand-written declarations are never
  touched — `forge_owned?/1` is how callers tell the difference. Because the
  slug is deterministic, re-adopting or overwriting the same resource rewrites
  the same file in place.

  Adopt is only offered for `:unmanaged` resources (observed but not declared),
  so an adopted file never collides with a hand-written declaration of the same
  key.
  """

  alias Mjolnir.Forge.Declarations

  @suffix ".adopted.exs"

  @doc "Absolute path of the adopted file for a resource (deterministic)."
  @spec adopted_path(String.t(), String.t(), String.t()) :: String.t()
  def adopted_path(host, kind, id) do
    Path.join(Declarations.path(), "forge-adopted-#{slug(host, kind, id)}#{@suffix}")
  end

  @doc "True if `path` is a file Forge authored (safe to overwrite/delete)."
  @spec forge_owned?(String.t()) :: boolean()
  def forge_owned?(path) when is_binary(path), do: String.ends_with?(path, @suffix)
  def forge_owned?(_), do: false

  @doc """
  Render and write the adopted declaration file for `{host, kind_mod, id}` with
  `content`. Atomic (tmp + rename). Returns `{:ok, path}` or `{:error, reason}`.
  """
  @spec write(String.t(), module(), String.t(), term()) ::
          {:ok, String.t()} | {:error, term()}
  def write(host, kind_mod, id, content) do
    path = adopted_path(host, kind_mod.kind(), id)
    source = render_module(host, kind_mod, id, content)
    tmp = path <> ".tmp"

    with :ok <- File.mkdir_p(Path.dirname(path)),
         :ok <- File.write(tmp, source),
         :ok <- File.rename(tmp, path) do
      {:ok, path}
    else
      {:error, _} = err ->
        _ = File.rm(tmp)
        err
    end
  end

  @doc "Remove the adopted file for a resource. Idempotent."
  @spec remove(String.t(), String.t(), String.t()) :: :ok | {:error, term()}
  def remove(host, kind, id) do
    case File.rm(adopted_path(host, kind, id)) do
      :ok -> :ok
      {:error, :enoent} -> :ok
      {:error, _} = err -> err
    end
  end

  @doc "The generated module source for a resource. Exposed for tests."
  @spec render_module(String.t(), module(), String.t(), term()) :: binary()
  def render_module(host, kind_mod, id, content) do
    block = kind_mod.to_declaration(id, content) |> IO.iodata_to_binary()

    """
    # Generated by Mjolnir.Forge adopt — safe to edit; Forge will overwrite on
    # re-adopt or overwrite-from-observed. Delete the file to stop managing it.
    defmodule #{module_name(host, kind_mod, id)} do
      use Mjolnir.Forge.Declaration, host: #{inspect(host)}

    #{indent(block)}
    end
    """
  end

  @doc "Deterministic module name for an adopted resource."
  @spec module_name(String.t(), module(), String.t()) :: String.t()
  def module_name(host, kind_mod, id) do
    "Mjolnir.Forge.Adopted.R#{slug(host, kind_mod.kind(), id)}"
  end

  ## Internals

  # 16 hex chars of sha256(host \0 kind \0 id) — collision-resistant, fixed
  # length, filesystem- and atom-safe.
  defp slug(host, kind, id) do
    :crypto.hash(:sha256, [host, 0, kind, 0, id])
    |> Base.encode16(case: :lower)
    |> binary_part(0, 16)
  end

  defp indent(block) do
    block
    |> String.split("\n")
    |> Enum.map_join("\n", fn
      "" -> ""
      line -> "  " <> line
    end)
  end
end
