#!/bin/bash
# Install mjolnir-blob-door on the Linux host. Does NOT restart Elixir.
#
# Usage (on the Mjolnir host, as root):
#   sudo bash scripts/install-blob-door.sh
#
# Binds 10.200.0.1:7222. Creates a B2 application key (read/write, not
# delete) if /etc/mjolnir/blob-door.env is missing, using the host's
# rclone b2 remote. Never prints secrets.

set -euo pipefail

ROOT="${MJOLNIR_CODE:-/opt/mjolnir}"
NATIVE="$ROOT/native"
BIN_DST="/opt/mjolnir/bin/mjolnir-blob-door"
UNIT_DST="/etc/systemd/system/mjolnir-blob-door.service"
ENV_DST="/etc/mjolnir/blob-door.env"
HOST_IP="${MJOLNIR_HOST_API_IP:-10.200.0.1}"
VM_SUBNET="${MJOLNIR_VM_SUBNET:-10.192.0.0/10}"
BUCKET="${B2_BUCKET:-mjolnir-blobs}"
CACHE_DIR="${BLOB_DOOR_CACHE_DIR:-/var/lib/mjolnir/btrfs/@blobs}"
CACHE_BYTES="${BLOB_DOOR_CACHE_BYTES:-68719476736}"
MAX_BYTES="${BLOB_DOOR_MAX_BYTES:-1099511627776}"

if [[ $EUID -ne 0 ]]; then
    echo "Error: run as root" >&2
    exit 1
fi

if ! ip addr show dummy-mjolnir 2>/dev/null | grep -q "inet ${HOST_IP}/32"; then
    echo "Error: ${HOST_IP}/32 is not assigned on dummy-mjolnir. Fail closed." >&2
    exit 1
fi

echo "=== Building mjolnir-blob-door ==="
export PATH="${HOME}/.cargo/bin:/root/.cargo/bin:${PATH}"
if ! command -v cargo >/dev/null; then
    echo "Error: cargo not on PATH (looked in ~/.cargo/bin)" >&2
    exit 1
fi
cd "$NATIVE"
# Linux host; crate does not need recrypt-core.
cargo build -p mjolnir-blob-door --release
install -d /opt/mjolnir/bin
install -m 0755 "$NATIVE/target/release/mjolnir-blob-door" "$BIN_DST"
install -m 0644 "$ROOT/systemd/mjolnir-blob-door.service" "$UNIT_DST"

ensure_cache_dir() {
    local parent
    parent="$(dirname "$CACHE_DIR")"
    if [[ -d "$parent" ]] && stat -f -c %T "$parent" 2>/dev/null | grep -qi btrfs; then
        if [[ ! -d "$CACHE_DIR" ]]; then
            echo "=== Creating BTRFS subvolume $CACHE_DIR ==="
            btrfs subvolume create "$CACHE_DIR"
        fi
    else
        mkdir -p "$CACHE_DIR"
    fi
    mkdir -p "$CACHE_DIR/objects" "$CACHE_DIR/incoming"
    chmod 700 "$CACHE_DIR"
}

ensure_env_key() {
    local file="$1" key="$2" value="$3"
    if grep -q "^${key}=" "$file" 2>/dev/null; then
        if [[ "$key" == "BLOB_DOOR_MAX_BYTES" ]]; then
            local cur
            cur="$(grep "^${key}=" "$file" | head -1 | cut -d= -f2-)"
            if [[ "$cur" == "67108864" ]]; then
                sed -i "s|^${key}=.*|${key}=${value}|" "$file"
            fi
        fi
    else
        echo "${key}=${value}" >> "$file"
    fi
}

provision_env() {
    if [[ -f "$ENV_DST" ]]; then
        echo "Keeping existing $ENV_DST"
        return 0
    fi

    local rclone_conf="${RCLONE_CONFIG:-/root/.config/rclone/rclone.conf}"
    if [[ ! -f "$rclone_conf" ]]; then
        echo "Error: $ENV_DST missing and no rclone.conf to mint a B2 key from" >&2
        exit 1
    fi

    echo "=== Provisioning B2 application key (no delete) into $ENV_DST ==="
    umask 077
    mkdir -p /etc/mjolnir
    python3 - "$rclone_conf" "$BUCKET" "$ENV_DST" "$HOST_IP" "$MAX_BYTES" "$CACHE_DIR" "$CACHE_BYTES" << 'PY'
import configparser, json, os, ssl, sys, urllib.request, urllib.error, base64

conf, bucket, dest, host_ip, max_bytes, cache_dir, cache_bytes = sys.argv[1:8]
cp = configparser.ConfigParser()
cp.read(conf)
if "b2" not in cp:
    sys.exit("rclone.conf has no [b2] remote")
account = cp["b2"]["account"]
key = cp["b2"]["key"]

ctx = ssl.create_default_context()

def post(url, payload, auth=None, token=None):
    data = json.dumps(payload).encode() if payload is not None else b""
    req = urllib.request.Request(url, data=data, method="POST")
    req.add_header("Content-Type", "application/json")
    if auth:
        req.add_header("Authorization", "Basic " + base64.b64encode(auth).decode())
    if token:
        req.add_header("Authorization", token)
    with urllib.request.urlopen(req, context=ctx) as resp:
        return json.load(resp)

req = urllib.request.Request("https://api.backblazeb2.com/b2api/v2/b2_authorize_account")
req.add_header("Authorization", "Basic " + base64.b64encode(f"{account}:{key}".encode()).decode())
with urllib.request.urlopen(req, context=ctx) as resp:
    auth = json.load(resp)
allowed = auth.get("allowed") or {}
# rclone b2 key is scoped to mimir-backups and cannot list/create buckets
# or mint a child key. Reuse it; the door has no DELETE route.
bucket = allowed.get("bucketName") or bucket
s3_ep = "https://s3.us-west-004.backblazeb2.com"
body = f"""# generated by scripts/install-blob-door.sh — never copy into a guest
BLOB_DOOR_BIND={host_ip}:7222
BLOB_DOOR_ALLOW_NONLOCAL=1
BLOB_DOOR_BACKEND=b2
BLOB_DOOR_MAX_BYTES={max_bytes}
BLOB_DOOR_CACHE_DIR={cache_dir}
BLOB_DOOR_CACHE_BYTES={cache_bytes}

B2_ENDPOINT={s3_ep}
B2_REGION=us-west-004
B2_BUCKET={bucket}
B2_KEY_ID={account}
B2_APPLICATION_KEY={key}
"""
tmp = dest + ".tmp"
with open(tmp, "w") as f:
    f.write(body)
os.chmod(tmp, 0o600)
os.replace(tmp, dest)
print("wrote", dest, "bucket", bucket, file=sys.stderr)
PY
}

provision_env
ensure_cache_dir
ensure_env_key "$ENV_DST" BLOB_DOOR_CACHE_DIR "$CACHE_DIR"
ensure_env_key "$ENV_DST" BLOB_DOOR_CACHE_BYTES "$CACHE_BYTES"
ensure_env_key "$ENV_DST" BLOB_DOOR_MAX_BYTES "$MAX_BYTES"

echo "=== INPUT allow TAP → ${HOST_IP}:7222 ==="
if command -v ufw >/dev/null && ufw status 2>/dev/null | grep -qi '^Status: active'; then
    if ! ufw status | grep -q "${HOST_IP} 7222"; then
        ufw allow proto tcp from "$VM_SUBNET" to "$HOST_IP" port 7222 comment 'VMs to blob door'
    fi
else
    if ! iptables -C INPUT -p tcp -s "$VM_SUBNET" -d "$HOST_IP" --dport 7222 -j ACCEPT 2>/dev/null; then
        iptables -A INPUT -p tcp -s "$VM_SUBNET" -d "$HOST_IP" --dport 7222 -j ACCEPT
    fi
fi

echo "=== systemd restart door (Elixir untouched) ==="
systemctl daemon-reload
systemctl enable mjolnir-blob-door
# enable --now will not pick up a replaced binary if the unit is already active
systemctl restart mjolnir-blob-door
sleep 1
curl -fsS "http://${HOST_IP}:7222/health"
echo
ss -lntp | grep 7222 || true
echo "=== blob door installed ==="
